name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0
      - name: Setup uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Test
        run: python main.py
      - name: Output Results to GitHub Summary
        run: cat results.md >> "$GITHUB_STEP_SUMMARY"
